spring:
    data:
      elasticsearch:
        cluster-nodes: 10.112.189.1:9300
        local: false
        properties:
          transport:
            tcp:
              connect_timeout:60s
        cluster:
          name: brain
  dubbo:
    registry:
      address: zookeeper://10.112.189.1:2181?backup=10.112.189.2:2181,10.112.189.5:2181
    protocol:
      name: dubbo
    protocol:
      port: 20882
      host: 10.112.189.5
      #host: 10.112.189.6
#10.112.189.6 ->112.35.28.192
#10.112.189.5 ->112.35.28.19
